#include "pch.h"
#include "EditorInputVector.h"

namespace Editor
{
    _EDITOR_WIDGET_INPUT_CLASS_CPP_DEFINE_NORMAL(InputInt,  ImGui::InputInt);
    _EDITOR_WIDGET_INPUT_CLASS_CPP_DEFINE_NORMAL(InputFloat, ImGui::InputFloat);
    _EDITOR_WIDGET_INPUT_CLASS_CPP_DEFINE_VECTOR(InputVector2, ImGui::InputFloat2);
    _EDITOR_WIDGET_INPUT_CLASS_CPP_DEFINE_VECTOR(InputVector3, ImGui::InputFloat3);
    _EDITOR_WIDGET_INPUT_CLASS_CPP_DEFINE_VECTOR(InputVector4, ImGui::InputFloat4);

    _EDITOR_WIDGET_DRAG_CLASS_CPP_DEFINE_NORMAL(DragInt, ImGui::DragInt);
    _EDITOR_WIDGET_DRAG_CLASS_CPP_DEFINE_NORMAL(DragFloat, ImGui::DragFloat);
    _EDITOR_WIDGET_DRAG_CLASS_CPP_DEFINE_VECTOR(DragVector2, ImGui::DragFloat2);
    _EDITOR_WIDGET_DRAG_CLASS_CPP_DEFINE_VECTOR(DragVector3, ImGui::DragFloat3);
    _EDITOR_WIDGET_DRAG_CLASS_CPP_DEFINE_VECTOR(DragVector4, ImGui::DragFloat4);
}